### ISSUE TITLE
Support unnamed structs

### ISSUE THREAD

**Issue by otaviopace** [otaviopace/edn-derive#17]
We still need to design it better: https://twitter.com/GirlGameDev/status/1306622222908510208

Handle it here: https://github.com/otaviopace/edn-derive/blob/99f36fe74d2b9698f9642ca0cc3853d16f86983c/src/structs.rs#L9

**Comment by otaviopace** [comment]
For now, the prefered way is from:
```rust
struct Abc(usize, String);
Abc(5, "Hello".to_string())
```
To something like:
```clojure
:Abc {0 5 1 "Hello"}
```

**Comment by naomijub** [comment]
https://github.com/otaviopace/edn-derive/pull/25
